### ISSUE TITLE
Suggestion: show rate limits to clients

### ISSUE THREAD

**Issue by bigwheels16** [Nadybot/highway#2]
For clients connecting to Highway, it would be nice to have a way to know the rates that are being used, possibly in the "hello" message:

```
{
  "type": "hello",
  "public-rooms": [
    "boss_timers",
    "update_notifications"
  ],
  "connections_per_ip": 50,
  "msg_per_sec": 10,
  "bytes_per_10_sec": 5242880,
  "max_message_size": 1048576,
  "max_frame_size": 1048576
}
```

This way the client will know what sort of rate limiting it should employ on its end.

**Comment by Gelbpunkt** [comment]
Hi, I've implemented this in the latest release (under a new `config` field in the hello payload). Please be aware that highway doesn't reject messages that exceed the rate limits (only those that exceed the frame or message size limit). Instead, it will block processing packets from the client until the rate limit isn't exhausted anymore. 

This means you usually won't have to care about the ratelimits themselves and only rather the connection and size limits, but I can see why it might be useful to do some rate limiting yourself.

This latest release will be deployed to the public relay tomorrow!
